// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NuclearInfrastructure.Repositories;

#nullable disable

namespace NuclearInfrastructure.Migrations
{
    [DbContext(typeof(ReactorDbContext))]
    [Migration("20260721123540_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConfigureCellCommandDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NewColumnType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ConfigureCellCommands");
                });

            modelBuilder.Entity("NuclearDomain.DTOs.CellDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReactorGridDtoId")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ActivityInfo", "NuclearDomain.DTOs.CellDto.ActivityInfo#ActivityInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("CreateDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean");

                            b1.Property<DateTime?>("UpdateDate")
                                .HasColumnType("timestamp with time zone");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Telemetry", "NuclearDomain.DTOs.CellDto.Telemetry#CellTelemetryDto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("LocalPowerOutputMW")
                                .HasColumnType("double precision");

                            b1.Property<double?>("RodInsertionDepth")
                                .HasColumnType("double precision");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("SteamQuality")
                                .HasColumnType("double precision");

                            b1.Property<double>("TemperatureCelsius")
                                .HasColumnType("double precision");

                            b1.Property<double>("WaterFlowRate")
                                .HasColumnType("double precision");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ReactorGridDtoId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("NuclearDomain.DTOs.MoveControlRodCommandDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("TargetInsertionPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MoveControlRodCommands");
                });

            modelBuilder.Entity("NuclearDomain.DTOs.ReactorGridDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalColumns")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ActivityInfo", "NuclearDomain.DTOs.ReactorGridDto.ActivityInfo#ActivityInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("CreateDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean");

                            b1.Property<DateTime?>("UpdateDate")
                                .HasColumnType("timestamp with time zone");
                        });

                    b.HasKey("Id");

                    b.ToTable("ReactorGrids");
                });

            modelBuilder.Entity("NuclearDomain.DTOs.ReactorOverviewDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageCoolantTemp")
                        .HasColumnType("double precision");

                    b.Property<double>("ControlRodAverageInsertion")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsScrammed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OperatingMargin")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalThermalPowerMW")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ReactorOverviews");
                });

            modelBuilder.Entity("NuclearDomain.DTOs.ScramReactorCommandDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsScrammed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScramReactorCommands");
                });

            modelBuilder.Entity("NuclearDomain.DTOs.CellDto", b =>
                {
                    b.HasOne("NuclearDomain.DTOs.ReactorGridDto", null)
                        .WithMany("Cells")
                        .HasForeignKey("ReactorGridDtoId");
                });

            modelBuilder.Entity("NuclearDomain.DTOs.ReactorGridDto", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
