// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NuclearInfrastructure.Repositories;

#nullable disable

namespace NuclearInfrastructure.Migrations
{
    [DbContext(typeof(ReactorDbContext))]
    [Migration("20260806122856_MonitoringUpdate-1.1V")]
    partial class MonitoringUpdate11V
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NuclearDomain.Entities.Cell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnType")
                        .HasColumnType("integer")
                        .HasColumnName("column_type");

                    b.Property<int>("ReactorGridId")
                        .HasColumnType("integer")
                        .HasColumnName("reactor_grid_id");

                    b.Property<string>("Telemetry")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("telemetry");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_cells");

                    b.HasIndex("ReactorGridId")
                        .HasDatabaseName("ix_cells_reactor_grid_id");

                    b.ToTable("cells", (string)null);
                });

            modelBuilder.Entity("NuclearDomain.Entities.ReactorGrid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMonitored")
                        .HasColumnType("boolean")
                        .HasColumnName("is_monitored");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean")
                        .HasColumnName("is_running");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TotalColumns")
                        .HasColumnType("integer")
                        .HasColumnName("total_columns");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ActivityInfo", "NuclearDomain.Entities.ReactorGrid.ActivityInfo#ActivityInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("CreateDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("activity_info_create_date");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("activity_info_is_active");

                            b1.Property<DateTime?>("UpdateDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("activity_info_update_date");
                        });

                    b.HasKey("Id")
                        .HasName("pk_reactor_grids");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_reactor_grids_name");

                    b.ToTable("reactor_grids", (string)null);
                });

            modelBuilder.Entity("NuclearDomain.Entities.Cell", b =>
                {
                    b.HasOne("NuclearDomain.Entities.ReactorGrid", "ReactorGrid")
                        .WithMany("Cells")
                        .HasForeignKey("ReactorGridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cells_reactor_grids_reactor_grid_id");

                    b.Navigation("ReactorGrid");
                });

            modelBuilder.Entity("NuclearDomain.Entities.ReactorGrid", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
