<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-NuclearEngine-9bed94d9-f0e9-4513-a4d3-a47521c7210e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\NuclearApp\NuclearApp.csproj" />
    <ProjectReference Include="..\src\NuclearInfrastructure\NuclearInfrastructure.csproj" />
  </ItemGroup>
</Project>
