using System;
using System.Collections.Generic;
using System.Text;
using NuclearApp.Interfaces.Services;
using NuclearDomain.Entities;
using NuclearDomain.Entities.Telemetries;

namespace NuclearApp.Services;

public class ReactorPhysicsEngine : IReactorPhysicsEngine
{
    private const double InfluenceRadius = 2.5;
    private const double FuelMassKg = 115.0;
    private const double GraphiteMassKg = 1400.0;
    private const double FuelCp = 0.00030;      // MJ / (kg * °C)
    private const double GraphiteCp = 0.00180;  // MJ / (kg * °C)

    // Core Feedback Coefficients
    private const double BaseKInfinitive = 1.05;        // Fresh 2.0% enriched UO2
    private const double DopplerCoefficient = -0.00004; // -Δk per °C fuel rise
    private const double VoidCoefficient = +0.00015;    // +Δk per % void (RBMK positive void effect)
    private const double FluxToMWFactor = 0.00005;     // Scaling factor: Thermal Flux -> MW

    private static readonly (int dx, int dy)[] Directions = new[]
    {
        (0, 1),   // Up
        (0, -1),  // Down
        (-1, 0),  // Left
        (1, 0)    // Right
    };

    public void ProcessPhysicsTick(ReactorGrid grid, double deltaTimeSeconds)
    {
        if (!grid.IsRunning || !grid.IsValid)
        {
            return;
        }

        var cellMap = grid.Cells.ToDictionary(c => (c.X, c.Y));

        // 1. Advance Mechanical Devices
        var controlRods = ControlRodsPhysics(grid, deltaTimeSeconds);

        // 2. Neutron Diffusion & Chain Reaction Pass
        ProcessDiffusionAndNeutronChain(cellMap, controlRods);

        // 3. Fuel Fission Power & Single-Source Thermal Heating
        FuelChannelPhysics(cellMap, deltaTimeSeconds, controlRods);

        // 4. Spatial Conduction & Thermal-Hydraulic Phase Change
        ProcessConductionAndPhaseChange(cellMap, deltaTimeSeconds);
    }

    private static List<Cell> ControlRodsPhysics(ReactorGrid grid, double deltaTimeSeconds)
    {
        var controlRods = grid.Cells
            .Where(c => c.ColumnType == ColumnType.ControlRods)
            .ToList();

        foreach (var rodCell in controlRods)
        {
            if (rodCell.Telemetry is ControlRodsTelemetryDto rodTelemetry)
            {
                rodTelemetry.MoveTick(deltaTimeSeconds);
            }
        }

        return controlRods;
    }

    private static void ProcessDiffusionAndNeutronChain(
        Dictionary<(int X, int Y), Cell> cellMap,
        List<Cell> controlRods)
    {
        var newFastFlux = new Dictionary<(int X, int Y), double>();
        var newThermalFlux = new Dictionary<(int X, int Y), double>();

        // 2A. Calculate local multiplication factor (k_eff) & Fission Fast Flux Generation
        foreach (var ((x, y), cell) in cellMap)
        {
            if (cell.ColumnType == ColumnType.FuelChannel && cell.Telemetry is FuelChannelTelemetryDto fuel)
            {
                if (!fuel.IsOnline || fuel.Status == FuelRodStatus.Meltdown)
                    continue;

                double nearbyVoidFraction = GetAverageNearbySteamQuality(cellMap, x, y);

                // Reactivity Feedbacks: Doppler (negative) + Void (positive)
                double deltaKDoppler = (fuel.TemperatureCelsius - 20.0) * DopplerCoefficient;
                double deltaKVoid = nearbyVoidFraction * VoidCoefficient * 100.0;
                double localK = BaseKInfinitive + deltaKDoppler + deltaKVoid;

                // Fission equation: Fast flux generated by thermal flux absorption
                double fissionFastFlux = fuel.ThermalFlux * localK;
                newFastFlux[(x, y)] = fissionFastFlux;
            }
        }

        // 2B. Spatial Diffusion across adjacent cells
        foreach (var ((x, y), cell) in cellMap)
        {
            if (cell.Telemetry is not CellTelemetry telemetry) continue;

            double outgoingFast = (telemetry.FastFlux * 0.15) / 4.0;
            double outgoingThermal = (telemetry.ThermalFlux * 0.10) / 4.0;

            foreach (var (dx, dy) in Directions)
            {
                var neighborPos = (x + dx, y + dy);
                if (!cellMap.TryGetValue(neighborPos, out var neighborCell))
                    continue;

                switch (neighborCell.ColumnType)
                {
                    case ColumnType.GraphiteModerator:
                        AddDelta(newThermalFlux, neighborPos, outgoingFast * 0.95);
                        break;

                    case ColumnType.Reflector:
                        AddDelta(newFastFlux, (x, y), outgoingFast * 0.85);
                        break;

                    case ColumnType.Absorber:
                        break;

                    case ColumnType.ControlRods:
                        if (neighborCell.Telemetry is ControlRodsTelemetryDto rod)
                        {
                            double passedThermal = outgoingThermal * (1.0 - rod.CurrentInsertionPercentage);
                            AddDelta(newThermalFlux, neighborPos, passedThermal);
                        }
                        break;

                    default:
                        AddDelta(newFastFlux, neighborPos, outgoingFast * 0.80);
                        AddDelta(newThermalFlux, neighborPos, outgoingThermal * 0.80);
                        break;
                }
            }
        }

        // Apply updated flux levels to telemetry models
        foreach (var ((x, y), cell) in cellMap)
        {
            if (cell.Telemetry is CellTelemetry t)
            {
                t.FastFlux = Math.Max(0.0, newFastFlux.GetValueOrDefault((x, y), 0.0));
                t.ThermalFlux = Math.Max(0.0, newThermalFlux.GetValueOrDefault((x, y), 0.0));
            }
        }
    }

    private static void FuelChannelPhysics(
        Dictionary<(int X, int Y), Cell> cellMap,
        double deltaTimeSeconds,
        List<Cell> controlRods)
    {
        foreach (var ((x, y), cell) in cellMap)
        {
            if (cell.ColumnType != ColumnType.FuelChannel || cell.Telemetry is not FuelChannelTelemetryDto fuelTelemetry)
                continue;

            if (!fuelTelemetry.IsOnline || fuelTelemetry.Status == FuelRodStatus.Meltdown)
            {
                fuelTelemetry.LocalPowerOutputMW = 0.0;
                fuelTelemetry.ExecutePhysicsTick(deltaTimeSeconds);
                continue;
            }

            // Calculate total control rod suppression within InfluenceRadius
            double totalSuppression = 0.0;
            foreach (var rodCell in controlRods)
            {
                if (rodCell.Telemetry is ControlRodsTelemetryDto rodTelemetry)
                {
                    double dx = cell.X - rodCell.X;
                    double dy = cell.Y - rodCell.Y;
                    double distance = Math.Sqrt(dx * dx + dy * dy);

                    if (distance <= InfluenceRadius)
                    {
                        double proximityFactor = 1.0 - (distance / InfluenceRadius);
                        totalSuppression += rodTelemetry.CurrentInsertionPercentage * proximityFactor;
                    }
                }
            }

            // Suppress effective thermal flux driving fission power
            double effectiveThermalFlux = Math.Max(0.0, fuelTelemetry.ThermalFlux * (1.0 - Math.Clamp(totalSuppression, 0.0, 1.0)));
            fuelTelemetry.LocalPowerOutputMW = effectiveThermalFlux * FluxToMWFactor;

            // Thermal energy generated (MJ = MW * seconds)
            double thermalEnergyGeneratedMJ = fuelTelemetry.LocalPowerOutputMW * deltaTimeSeconds;

            // Single source of heating truth
            double deltaT = thermalEnergyGeneratedMJ / (FuelMassKg * FuelCp);
            fuelTelemetry.TemperatureCelsius += deltaT;

            fuelTelemetry.ExecutePhysicsTick(deltaTimeSeconds);
        }
    }

    private static void ProcessConductionAndPhaseChange(
        Dictionary<(int X, int Y), Cell> cellMap,
        double deltaTimeSeconds)
    {
        const double ThermalConductivity = 0.05;
        var energyTransfersMJ = new Dictionary<(int X, int Y), double>();

        // Conduction transfers based on local temperature gradients
        foreach (var ((x, y), cell) in cellMap)
        {
            if (cell.Telemetry is not CellTelemetry source) continue;

            foreach (var (dx, dy) in Directions)
            {
                var neighborPos = (x + dx, y + dy);
                if (cellMap.TryGetValue(neighborPos, out var neighbor) && neighbor.Telemetry is CellTelemetry target)
                {
                    double tempDiff = source.TemperatureCelsius - target.TemperatureCelsius;
                    if (tempDiff > 0)
                    {
                        double energyTransferredMJ = tempDiff * ThermalConductivity * deltaTimeSeconds;
                        AddDelta(energyTransfersMJ, (x, y), -energyTransferredMJ);
                        AddDelta(energyTransfersMJ, neighborPos, energyTransferredMJ);
                    }
                }
            }
        }

        // Apply Conduction Deltas & Execute Steam Channel Phase Change
        foreach (var ((x, y), cell) in cellMap)
        {
            if (cell.Telemetry is not CellTelemetry telemetry) continue;

            double netEnergyMJ = energyTransfersMJ.GetValueOrDefault((x, y), 0.0);

            if (cell.ColumnType == ColumnType.SteamChannel && cell.Telemetry is SteamChannelTelemetryDto steam)
            {
                steam.ProcessCoolingAndSteam(netEnergyMJ, 25.0, deltaTimeSeconds);
            }
            else
            {
                double mass = cell.ColumnType == ColumnType.GraphiteModerator ? GraphiteMassKg : FuelMassKg;
                double cp = cell.ColumnType == ColumnType.GraphiteModerator ? GraphiteCp : FuelCp;

                telemetry.TemperatureCelsius = Math.Max(20.0, telemetry.TemperatureCelsius + (netEnergyMJ / (mass * cp)));
            }
        }
    }

    private static double GetAverageNearbySteamQuality(Dictionary<(int X, int Y), Cell> cellMap, int x, int y)
    {
        double totalQuality = 0.0;
        int count = 0;

        foreach (var (dx, dy) in Directions)
        {
            if (cellMap.TryGetValue((x + dx, y + dy), out var neighbor) &&
                neighbor.ColumnType == ColumnType.SteamChannel &&
                neighbor.Telemetry is SteamChannelTelemetryDto steam)
            {
                totalQuality += steam.SteamQuality;
                count++;
            }
        }

        return count > 0 ? totalQuality / count : 0.0;
    }

    private static void AddDelta(Dictionary<(int X, int Y), double> dict, (int X, int Y) key, double value)
    {
        dict[key] = dict.GetValueOrDefault(key, 0.0) + value;
    }
}